let g:mapleader = "\<Space>"

" Reload vim on all changes
augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

" Immediately set up and install vim-plug and plugins if they don't exist
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

" Source vim-plug plugins defined in the module/ directory
call plug#begin('~/.vim/plugged')
runtime! module/**/*.vim
call plug#end()

" Disable Netrw
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1

