#!/bin/sh

this_script=~/.local/tools/rofing
layout_dir=~/.local/bin/xrandr

options=(
Layouts
Window
Apps
SSH
)

case "$1" in
  Picker)
    option=$(printf '%s\n' "${options[@]}" | rofi -dmenu)
    if [ $? == 0 ]; then
      $this_script $option
    fi
  ;;

  Layouts)
    layout=$(\ls $layout_dir | rofi -dmenu)
    if [ $? == 0 ]; then
      # lxsu
      $layout_dir/$layout
    fi
  ;;

  Window)
    rofi -show window
  ;;

  Apps)
    rofi -show run
  ;;

  SSH)
    rofi -show ssh
  ;;

  *)
    rofi -combi-modi window,drun -show combi -modi combi
    ;;
esac

